name: fireflutter_sample_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  get: ^3.15.0
  country_code_picker: ^1.6.2
  fireflutter: ^0.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
